services:
  - type: web
    name: MultiTenant-SaaS
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "chmod +x render_start.sh && ./render_start.sh"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DATABASE_URL
        fromDatabase:
          name: saas-db
          property: connectionString
      - key: CELERY_BROKER_URL
        sync: false # You will paste your Aiven URL here manually

databases:
  - name: saas-db
    plan: free
    databaseName: saas
    user: admin